config/routes.rb
LittleWorld::Application.routes.draw do
  root :to => "friends#index"
  resources :friends
end

app/models/friend.rb
class Friend < ActiveRecord::Base

  validates :name, :latitude, :longitude, :presence => true
  validate :uniqueness_place

  scope :closests, -> friend { order("(longitude::double precision - (#{friend.longitude}))^2 +
          (latitude::double precision - (#{friend.latitude}))^2").where('id <> ?', friend.id).limit(3) }

  private

    def uniqueness_place
      friend = Friend.where(:latitude => latitude, :longitude => longitude).first
      errors.add(:base, ':uniqueness_place') if friend
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_filter :get_friend, :except => [:index, :new, :create]

  def index
    @friends = Friend.all
  end

  def show
    @closest_friends = Friend.closests(@friend)
  end

  def new
    @friend = Friend.new
  end

  def edit

  end

  def create
    @friend = Friend.new(friend_params)
    if @friend.save
      redirect_to @friend, :notice => t('flash.friends.create.notice')
    else
      flash.alert = t('flash.friends.create.alert')
      render :new
    end
  end

  def update
    if @friend.update(friend_params)
      redirect_to @friend, :notice => t('flash.friends.update.notice')
    else
      flash.alert = t('flash.friends.update.alert')
      render :edit
    end
  end

  def destroy
    if @friend.destroy
      redirect_to friends_path, :notice => t('flash.friends.destroy.notice')
    else
      redirect_to @friend, :alert => t('flash.friends.destroy.alert')
    end
  end

  private

  def friend_params
    params.require(:friend).permit(:name, :latitude, :longitude)
  end

  def get_friend
    @friend = Friend.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/friends/_form.html.erb
<%= provide :script_header do %>

<% end %>
<%= form_for @friend, :html => { :class => 'form-horizontal' } do |f| %>
    <%= render 'shared/error_messages', :object => @friend %>
   <div class = 'row'>
     <div class = 'span5'>
       <div class="control-group">
         <%= f.label :name, :class => 'control-label' %>
         <div class="controls">
           <%= f.text_field :name, :class => 'text_field' %>
         </div>
       </div>
       <div class="control-group">
         <%= f.label :latitude, :class => 'control-label' %>
         <div class="controls">
           <%= f.text_field :latitude, :class => 'text_field' %>
         </div>
       </div>
       <div class="control-group">
         <%= f.label :longitude, :class => 'control-label' %>
         <div class="controls">
           <%= f.text_field :longitude, :class => 'text_field' %>
         </div>
       </div>
     </div>
     <div class = 'span5'>
       <div id="map"></div>
     </div>
   </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                friends_path, :class => 'btn' %>
  </div>
<% end %>

<script type="text/javascript">
    ////map
    var map = new GMap2(document.getElementById("map"));
    //var start = new GLatLng(65,25);
    var lat = -16;
    var lng = -49;
    if (document.getElementById('friend_latitude').value !== '') {
        lat = document.getElementById('friend_latitude').value;
    }
    if (document.getElementById('friend_longitude').value !== '') {
        lng = document.getElementById('friend_longitude').value;
    }

    map.setCenter(new GLatLng(lat,lng), 4);
    map.addControl(new GMapTypeControl(1));
    map.addControl(new GLargeMapControl());

    map.enableContinuousZoom();
    map.enableDoubleClickZoom();
    map.enableScrollWheelZoom ();



    // "tiny" marker icon
    var icon = new GIcon();
    icon.iconSize = new GSize(12, 20);
    icon.shadowSize = new GSize(22, 20);
    icon.iconAnchor = new GPoint(6, 20);
    icon.infoWindowAnchor = new GPoint(5, 1);



    /////Draggable markers


    var point = new GLatLng(lat,lng);
    var marker = new GMarker(point, {icon:G_DEFAULT_ICON, draggable: true});
    map.addOverlay(marker);

    marker.enableDragging();

    GEvent.addListener(marker, "drag", function(){
        document.getElementById('friend_latitude').value = marker.getLatLng().lat();
        document.getElementById('friend_longitude').value = marker.getLatLng().lng();
    });

    //]]>
</script>

app/views/friends/edit.html.erb
<%- model_class = Friend -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/friends/index.html.erb
<%- model_class = Friend -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= link_to friend.id, friend_path(friend), :title => t('helpers.links.show') %></td>
        <td><%= friend.name %></td>
        <td>
          <%= link_to t("helpers.links.show"),
                      friend_path(friend), :class => 'btn btn-success' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_friend_path(friend), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      friend_path(friend),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_friend_path,
            :class => 'btn btn-primary' %>

app/views/friends/new.html.erb
<%- model_class = Friend -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/friends/show.html.erb
<%= provide :script_header do %>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    <script>
        var marker_place = new google.maps.LatLng(<%= @friend.latitude %>,<%= @friend.longitude %> )
        function initialize() {
            var mapOptions = {
                zoom: 18,
                center: marker_place,
                mapTypeId: google.maps.MapTypeId.HYBRID
            };
            var map = new google.maps.Map(document.getElementById('map_canvas'),
                    mapOptions);
            marker = new google.maps.Marker({
                map:map,
                draggable:false,
                animation: google.maps.Animation.DROP,
                position: marker_place
            });
            google.maps.event.addListener(marker, 'click', toggleBounce);
        }

        google.maps.event.addDomListener(window, 'load', initialize);
    </script>
<% end %>
<%- model_class = Friend -%>
<div class="page-header">
  <h1><%= @friend.name %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:latitude) %>:</strong></dt>
  <dd><%= @friend.latitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:longitude) %>:</strong></dt>
  <dd><%= @friend.longitude %></dd>
</dl>

<div>
  <h4><%=t 'activerecord.models.friend.closests' %></h4>
  <ul class="nav nav-pills nav-stacked" >
    <% @closest_friends.each do |friend| %>
      <li><%= link_to friend.name, friend, :title => t('helpers.links.show') %> </li>
    <% end %>
  </ul>
</div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              friends_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_friend_path(@friend), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              friend_path(@friend),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "LittleWorld" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <script src="http://maps.google.com/maps?file=api&v=2&key=AIzaSyDRDdeQKJgRTnnQFyLNwd5affvHM1MZRbY"type="text/javascript">
    </script>
  </head>
  <body>

    <div class="navbar navbar-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to t('site_title'), root_path, :class => 'brand' %>
          <div class="container nav-collapse">
            <ul class="nav">

            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>

        </div><!--/row-->

      <footer>
        <p>&copy; DefIndex 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/shared/_error_messages.html.erb
<div class="container">
  <% if object.errors.any? %>
      <div class="mensagens msg-red">
        <ul>
          <% object.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
  <% end %>
</div>